######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 14 16:26:28 2014
######################################################################

TEMPLATE = app
TARGET = NcMonDemo
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lNcMonIO

# Input
HEADERS += DlgNcMonDemo.h NcMonInterface.h
SOURCES += DlgNcMonDemo.cpp main.cpp
