$axure.loadCurrentPage({
  "url":"梦想基金.html",
  "generationDate":new Date(1440388817931),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"94502349420d4e048934e7a672e730ee",
    "type":"Axure:Page",
    "name":"梦想基金",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cce16c4b29034dd28eb437edfe131d59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":152,
              "y":2},
            "size":{
              "width":1550,
              "height":33},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c33958c0fae94c8a8b233bd73aaba487",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":152,
                  "y":2},
                "size":{
                  "width":1550,
                  "height":33},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u5.png"}},
{
          "id":"913b3fb461fc4a0c88bf2796f97bcef6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":450,
              "y":9},
            "size":{
              "width":183,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c5e4da5a494a12aad247e0fb24f552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":450,
                  "y":9},
                "size":{
                  "width":183,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cc17c1685964d84a337e06ebba00cf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1488,
              "y":9},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e7a84b54744683875572412784260f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1488,
                  "y":9},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb6e275d58cd4d87a138476f7c875a65",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEF4349,
              "opacity":1},
            "location":{
              "x":1528,
              "y":9},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf5ab88aed9042d78499829c8e951f18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEF4349,
                  "opacity":1},
                "location":{
                  "x":1528,
                  "y":9},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df9efe0b1c4a46bf8aab8526792ea685",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1384,
              "y":9},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15ec7072c9df4186b02f2f03f2d26700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1384,
                  "y":9},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8408406428e466bba14f8f2462671ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":56},
            "size":{
              "width":80,
              "height":70},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fcf5de7ae3349dbad1640a117eadfdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":422,
                  "y":56},
                "size":{
                  "width":80,
                  "height":70},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u15.png"}},
{
          "id":"e43844aa2f83439fae4221b19b1b054a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD0B068,
              "opacity":1},
            "location":{
              "x":521,
              "y":67},
            "size":{
              "width":41,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"386d9962ccda4bb2a7a03f1516b05b97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD0B068,
                  "opacity":1},
                "location":{
                  "x":521,
                  "y":67},
                "size":{
                  "width":41,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bedb23ecd4d24ed4966fb294eb9e3d55",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":582,
              "y":83},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dcd948d97574bc1bbdd0d7290971556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":582,
                  "y":83},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9014340bd914ae7ba4d10f209f7a9d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":430,
              "y":99},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"741e31684bd54ba6b51fa0096b11238a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":430,
                  "y":99},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6642e9473f7a4a2d9dae7c3599fbe4f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":5},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d357082ae444bfb94f561e5092afcc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":412,
                  "y":5},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u149.png"}},
{
          "id":"e700195246b74d23a6b3f176d65210b8",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1517,
              "y":14},
            "size":{
              "width":10,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u151_line.png"}},
{
          "id":"a989898b8712433b95a1d1340847cffb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":957,
              "y":81},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7762fa53b1a4495281a42bab155d719f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":957,
                  "y":81},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"523ff43e6b54411ebed85fb28b90c669",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1414,
              "y":80},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28999c1ae281466c8983bffd260474de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1414,
                  "y":80},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 创客资讯",
                      "target":{
                        "targetType":"page",
                        "url":"创客资讯.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dfb2fa8a6c24ddbab562a9782a622a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC3300,
              "opacity":1},
            "location":{
              "x":1058,
              "y":81},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbdd72113cff4a1f89f20774baecadd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC3300,
                  "opacity":1},
                "location":{
                  "x":1058,
                  "y":81},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 梦想基金",
                      "target":{
                        "targetType":"page",
                        "url":"梦想基金.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"517869d9a7574d24b796efd6d3fe2222",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1175,
              "y":81},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d38ae7925d60406cb107b869c28ba6f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1175,
                  "y":81},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 工厂联盟",
                      "target":{
                        "targetType":"page",
                        "url":"工厂联盟.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c37d47f2d6c8429ba776884644b29d4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1296,
              "y":81},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1261b01e20cc43e5add30fdcdb97b4f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1296,
                  "y":81},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 项目展示",
                      "target":{
                        "targetType":"page",
                        "url":"项目展示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"259fe12e40c24d5a9cc984945ae6daec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":149},
            "size":{
              "width":1425,
              "height":1391},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ccb312c771443eba635d2c7d7db191d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":149},
                "size":{
                  "width":1425,
                  "height":1391},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/梦想基金/u31.png"}},
{
          "id":"bf5bef9afc3b463ca72cf254f241a70c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF484B54},
            "location":{
              "x":152,
              "y":1539},
            "size":{
              "width":1550,
              "height":223}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8191b9b524204c6cb1231e417e240739",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF484B54},
                "location":{
                  "x":152,
                  "y":1539},
                "size":{
                  "width":1550,
                  "height":223}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u253.png"}},
{
          "id":"d66002ade7b94c91ba8507ba99fb1a33",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD0B068,
              "opacity":1},
            "location":{
              "x":386,
              "y":1581},
            "size":{
              "width":90,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5320031cf7a47dab273f495103e374a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD0B068,
                  "opacity":1},
                "location":{
                  "x":386,
                  "y":1581},
                "size":{
                  "width":90,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6856463fca7c46b3a33de591f85325fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":386,
              "y":1615},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95b654512d0e452e96d8e05de6d8e542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":386,
                  "y":1615},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20e01944f2e24f5db207053fac9e4a1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":386,
              "y":1643},
            "size":{
              "width":125,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22425316cf0d46f1b9dc54c3cfc99a4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":386,
                  "y":1643},
                "size":{
                  "width":125,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6eb7eb945f31449fbea8b1a1d7f62cbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":386,
              "y":1679},
            "size":{
              "width":139,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0be74fafd754bd793eef2f574a19326",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":386,
                  "y":1679},
                "size":{
                  "width":139,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c223cc2dea07425487887e936d8a1d01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":386,
              "y":1705},
            "size":{
              "width":211,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"befc05619dd44abd9f5df5b31996cb60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":386,
                  "y":1705},
                "size":{
                  "width":211,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eda96821a1f24aa9a62dcd78589a7706",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":652,
              "y":1573},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dc46e409659421287eadc7fd417dcf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":652,
                  "y":1573},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e2240c11d0e4521b140909f04402a35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":811,
              "y":1573},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c4ca92d93ff4c808fde72bb9d2ff1f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":811,
                  "y":1573},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c236dd2b5b247799e24bfe930704f52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":953,
              "y":1571},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"827dfe02f1d0407db89e7e80b1d6265e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":953,
                  "y":1571},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d39159bbecc54f16879ad5bcdeee6127",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":1212,
              "y":1573},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6190e27a7a047b8831e20feeb1200ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":1212,
                  "y":1573},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cba5813ee42c41f6b94b1baa4f7d9de3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":1072,
              "y":1569},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8ca267ef4fe4fb59b1c64eb789f7529",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":1072,
                  "y":1569},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33030ad04a3b4b5892f97f7ea7e1813a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1218,
              "y":1603},
            "size":{
              "width":112,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39057e2f2cc14014939c0d8de2f372e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1218,
                  "y":1603},
                "size":{
                  "width":112,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u275.png"}},
{
          "id":"1126bd1749984037a7d61f56f07302b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1222,
              "y":1713},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1f56f5aa7834626ba6b3dbdf80d5f36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":1222,
                  "y":1713},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "cce16c4b29034dd28eb437edfe131d59":{
      "scriptId":"u0"},
    "c33958c0fae94c8a8b233bd73aaba487":{
      "scriptId":"u1"},
    "913b3fb461fc4a0c88bf2796f97bcef6":{
      "scriptId":"u2"},
    "e9c5e4da5a494a12aad247e0fb24f552":{
      "scriptId":"u3"},
    "1cc17c1685964d84a337e06ebba00cf2":{
      "scriptId":"u4"},
    "b4e7a84b54744683875572412784260f":{
      "scriptId":"u5"},
    "fb6e275d58cd4d87a138476f7c875a65":{
      "scriptId":"u6"},
    "bf5ab88aed9042d78499829c8e951f18":{
      "scriptId":"u7"},
    "df9efe0b1c4a46bf8aab8526792ea685":{
      "scriptId":"u8"},
    "15ec7072c9df4186b02f2f03f2d26700":{
      "scriptId":"u9"},
    "a8408406428e466bba14f8f2462671ec":{
      "scriptId":"u10"},
    "8fcf5de7ae3349dbad1640a117eadfdc":{
      "scriptId":"u11"},
    "e43844aa2f83439fae4221b19b1b054a":{
      "scriptId":"u12"},
    "386d9962ccda4bb2a7a03f1516b05b97":{
      "scriptId":"u13"},
    "bedb23ecd4d24ed4966fb294eb9e3d55":{
      "scriptId":"u14"},
    "5dcd948d97574bc1bbdd0d7290971556":{
      "scriptId":"u15"},
    "f9014340bd914ae7ba4d10f209f7a9d4":{
      "scriptId":"u16"},
    "741e31684bd54ba6b51fa0096b11238a":{
      "scriptId":"u17"},
    "6642e9473f7a4a2d9dae7c3599fbe4f2":{
      "scriptId":"u18"},
    "7d357082ae444bfb94f561e5092afcc0":{
      "scriptId":"u19"},
    "e700195246b74d23a6b3f176d65210b8":{
      "scriptId":"u20"},
    "a989898b8712433b95a1d1340847cffb":{
      "scriptId":"u21"},
    "7762fa53b1a4495281a42bab155d719f":{
      "scriptId":"u22"},
    "523ff43e6b54411ebed85fb28b90c669":{
      "scriptId":"u23"},
    "28999c1ae281466c8983bffd260474de":{
      "scriptId":"u24"},
    "4dfb2fa8a6c24ddbab562a9782a622a0":{
      "scriptId":"u25"},
    "bbdd72113cff4a1f89f20774baecadd9":{
      "scriptId":"u26"},
    "517869d9a7574d24b796efd6d3fe2222":{
      "scriptId":"u27"},
    "d38ae7925d60406cb107b869c28ba6f3":{
      "scriptId":"u28"},
    "c37d47f2d6c8429ba776884644b29d4a":{
      "scriptId":"u29"},
    "1261b01e20cc43e5add30fdcdb97b4f3":{
      "scriptId":"u30"},
    "259fe12e40c24d5a9cc984945ae6daec":{
      "scriptId":"u31"},
    "6ccb312c771443eba635d2c7d7db191d":{
      "scriptId":"u32"},
    "bf5bef9afc3b463ca72cf254f241a70c":{
      "scriptId":"u33"},
    "8191b9b524204c6cb1231e417e240739":{
      "scriptId":"u34"},
    "d66002ade7b94c91ba8507ba99fb1a33":{
      "scriptId":"u35"},
    "e5320031cf7a47dab273f495103e374a":{
      "scriptId":"u36"},
    "6856463fca7c46b3a33de591f85325fc":{
      "scriptId":"u37"},
    "95b654512d0e452e96d8e05de6d8e542":{
      "scriptId":"u38"},
    "20e01944f2e24f5db207053fac9e4a1c":{
      "scriptId":"u39"},
    "22425316cf0d46f1b9dc54c3cfc99a4e":{
      "scriptId":"u40"},
    "6eb7eb945f31449fbea8b1a1d7f62cbc":{
      "scriptId":"u41"},
    "d0be74fafd754bd793eef2f574a19326":{
      "scriptId":"u42"},
    "c223cc2dea07425487887e936d8a1d01":{
      "scriptId":"u43"},
    "befc05619dd44abd9f5df5b31996cb60":{
      "scriptId":"u44"},
    "eda96821a1f24aa9a62dcd78589a7706":{
      "scriptId":"u45"},
    "9dc46e409659421287eadc7fd417dcf5":{
      "scriptId":"u46"},
    "7e2240c11d0e4521b140909f04402a35":{
      "scriptId":"u47"},
    "8c4ca92d93ff4c808fde72bb9d2ff1f0":{
      "scriptId":"u48"},
    "9c236dd2b5b247799e24bfe930704f52":{
      "scriptId":"u49"},
    "827dfe02f1d0407db89e7e80b1d6265e":{
      "scriptId":"u50"},
    "d39159bbecc54f16879ad5bcdeee6127":{
      "scriptId":"u51"},
    "f6190e27a7a047b8831e20feeb1200ef":{
      "scriptId":"u52"},
    "cba5813ee42c41f6b94b1baa4f7d9de3":{
      "scriptId":"u53"},
    "b8ca267ef4fe4fb59b1c64eb789f7529":{
      "scriptId":"u54"},
    "33030ad04a3b4b5892f97f7ea7e1813a":{
      "scriptId":"u55"},
    "39057e2f2cc14014939c0d8de2f372e3":{
      "scriptId":"u56"},
    "1126bd1749984037a7d61f56f07302b2":{
      "scriptId":"u57"},
    "b1f56f5aa7834626ba6b3dbdf80d5f36":{
      "scriptId":"u58"}}});