$axure.loadCurrentPage({
  "url":"创客资讯.html",
  "generationDate":new Date(1440388817585.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"34a3facd3a6842039dd38528c0bd1a65",
    "type":"Axure:Page",
    "name":"创客资讯",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a1766c34ddd14a41baf0ef6765fa5622",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":152,
              "y":2},
            "size":{
              "width":1550,
              "height":33},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fb1a62a708d43a4aadf75fad6a8d6b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":152,
                  "y":2},
                "size":{
                  "width":1550,
                  "height":33},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u5.png"}},
{
          "id":"03e4c7b7ccbc4ef2908dcc6801452085",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":450,
              "y":9},
            "size":{
              "width":183,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2472aea50ef44c9bd7c77158f7ee610",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":450,
                  "y":9},
                "size":{
                  "width":183,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27ec87a4cce440c68d858e83e9384627",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1488,
              "y":9},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b25837022642eca88434d4f39b4f6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1488,
                  "y":9},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9eb91e1e86e48f3a0c2c3c905f5ba58",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEF4349,
              "opacity":1},
            "location":{
              "x":1528,
              "y":9},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bf71b06c3b748499a63f982cac1df7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEF4349,
                  "opacity":1},
                "location":{
                  "x":1528,
                  "y":9},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad4a3fec3df54b0381f66d7d9f723148",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1384,
              "y":9},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53fa5db354724584801e755e3a0ce58a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1384,
                  "y":9},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b5719051460410c93dd68eedc5585cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":56},
            "size":{
              "width":80,
              "height":70},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e980ba8d3174364a11da33d42d1b6fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":422,
                  "y":56},
                "size":{
                  "width":80,
                  "height":70},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u15.png"}},
{
          "id":"da55e65a56654a3c9b4fc81538545ee0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD0B068,
              "opacity":1},
            "location":{
              "x":521,
              "y":67},
            "size":{
              "width":41,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89edbb79e26243bc91a5a20ad13dd253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD0B068,
                  "opacity":1},
                "location":{
                  "x":521,
                  "y":67},
                "size":{
                  "width":41,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82ca7c2763494d37b714a697427be3ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":582,
              "y":83},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"875cef2a1139495398bab91d8b0429d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":582,
                  "y":83},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e75ecdfebba44fbba22b377bb12e95a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":430,
              "y":99},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"015585c7de3b48679743ffb75068ba29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":430,
                  "y":99},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7a1143e86d14cdd833609ce251f1c23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":5},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa79bfd34c554168bd4ba72e791fb612",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":412,
                  "y":5},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u149.png"}},
{
          "id":"0c54518016bc456e8fa6bf252d1ce22e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1517,
              "y":14},
            "size":{
              "width":10,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u151_line.png"}},
{
          "id":"2deb4a144b5f46a0b49a273c10f4737f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":136},
            "size":{
              "width":1550,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创客资讯/u21_line.png"}},
{
          "id":"3a730ed4d6634010bdf62d9959250d90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":164},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c9eee0ca9dc4529918893becfcab736",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":446,
                  "y":164},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"759f27a799944c028bb2fecc8c65e142",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":460,
              "y":200},
            "size":{
              "width":110,
              "height":810},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6a0827bb0984b20ae97c0bf82761987",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":460,
                  "y":200},
                "size":{
                  "width":110,
                  "height":810},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创客资讯/u24.png"}},
{
          "id":"75cb586b51a64e5bb3a37b758fba9df8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003366,
              "opacity":1},
            "location":{
              "x":594,
              "y":220},
            "size":{
              "width":556,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec11ae283f16483e94f4827c005d2385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003366,
                  "opacity":1},
                "location":{
                  "x":594,
                  "y":220},
                "size":{
                  "width":556,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 资讯详情",
                      "target":{
                        "targetType":"page",
                        "url":"资讯详情.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f86444b59f334ede879ab1b18c07c635",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":594,
              "y":257},
            "size":{
              "width":666,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d31e2582aee43c2a612eb3f5d52afc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":594,
                  "y":257},
                "size":{
                  "width":666,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d2db47448634abcace4d74763f6e95e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003366,
              "opacity":1},
            "location":{
              "x":610,
              "y":340},
            "size":{
              "width":490,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bcb1368d5ec473e82746055d9f6a10e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003366,
                  "opacity":1},
                "location":{
                  "x":610,
                  "y":340},
                "size":{
                  "width":490,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 资讯详情",
                      "target":{
                        "targetType":"page",
                        "url":"资讯详情.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95c5dd84ed99419c8aee7b7d6e3ef987",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":594,
              "y":320},
            "size":{
              "width":816,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创客资讯/u32_line.png"}},
{
          "id":"6aed5fcc2f6f479a8f7f5f06dfb30872",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":600,
              "y":375},
            "size":{
              "width":660,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04f4e0bf69c14831868546d9fbd8b235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":600,
                  "y":375},
                "size":{
                  "width":660,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29c7e349ee4d4d1da6b9641a0fe39ef6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":594,
              "y":441},
            "size":{
              "width":816,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创客资讯/u32_line.png"}},
{
          "id":"6c66194352bb4f02904fa399364df7c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":600,
              "y":492},
            "size":{
              "width":660,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b9d6050b9f54125878e239cee6d6f72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":600,
                  "y":492},
                "size":{
                  "width":660,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79c8ed3fe8ad40f68664e5acf43cbb75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003366,
              "opacity":1},
            "location":{
              "x":606,
              "y":461},
            "size":{
              "width":490,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35ad751eb7ef4290a1f1af18cc8acb0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003366,
                  "opacity":1},
                "location":{
                  "x":606,
                  "y":461},
                "size":{
                  "width":490,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 资讯详情",
                      "target":{
                        "targetType":"page",
                        "url":"资讯详情.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ece9f3bae814e5580f0056d37be6ad7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003366,
              "opacity":1},
            "location":{
              "x":600,
              "y":570},
            "size":{
              "width":556,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6e4fcc745134254a0308a7bf4534250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003366,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":570},
                "size":{
                  "width":556,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42fc5572f9fd452d9b9fbec42b14c7fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":600,
              "y":607},
            "size":{
              "width":666,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d3a63ddd60b451b8182af3ac7df46ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":600,
                  "y":607},
                "size":{
                  "width":666,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d70af83852f48b5b25bc66b39172431",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003366,
              "opacity":1},
            "location":{
              "x":616,
              "y":690},
            "size":{
              "width":490,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f64d4543e2454f5faf435ea371fe4f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003366,
                  "opacity":1},
                "location":{
                  "x":616,
                  "y":690},
                "size":{
                  "width":490,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"555a7191c6bd468689e2968e8cbd54d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":670},
            "size":{
              "width":816,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创客资讯/u32_line.png"}},
{
          "id":"f19296e01d8640fe891a6ebf1e65f540",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":606,
              "y":725},
            "size":{
              "width":660,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25fffc371ac14d7f8594dcb790100cbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":606,
                  "y":725},
                "size":{
                  "width":660,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24ecf040457745baad6e20a6055190b6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":791},
            "size":{
              "width":816,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创客资讯/u32_line.png"}},
{
          "id":"3604dca8abea42d086bd896a9e165110",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":606,
              "y":842},
            "size":{
              "width":660,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"087d468e406444d5b3d79d84ffa74cd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":606,
                  "y":842},
                "size":{
                  "width":660,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ad9b4a042464fb5a0965333198fccff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003366,
              "opacity":1},
            "location":{
              "x":612,
              "y":811},
            "size":{
              "width":490,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2af1af98e85f460599d3db1ecc5c9749",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003366,
                  "opacity":1},
                "location":{
                  "x":612,
                  "y":811},
                "size":{
                  "width":490,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef96d140699e4e12af6d1f043478a1da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF484B54},
            "location":{
              "x":302,
              "y":1123},
            "size":{
              "width":1550,
              "height":223}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30e2336a700a4cfdb34eb4d2ca8c3b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF484B54},
                "location":{
                  "x":302,
                  "y":1123},
                "size":{
                  "width":1550,
                  "height":223}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u253.png"}},
{
          "id":"3b67b98bb699460c9b1e055e5d05b74f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD0B068,
              "opacity":1},
            "location":{
              "x":536,
              "y":1164},
            "size":{
              "width":90,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d4fe5f943ab4478bec6cd3aab90501c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD0B068,
                  "opacity":1},
                "location":{
                  "x":536,
                  "y":1164},
                "size":{
                  "width":90,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1418e8565ded4cd7b36f8ea562429505",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":536,
              "y":1198},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e744b65828845eeabb7bfb1978baf78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":536,
                  "y":1198},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da1bc00ebe364f62958dc359aa12c626",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":536,
              "y":1226},
            "size":{
              "width":125,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9ed3fd522e448339ac18f585869f468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":536,
                  "y":1226},
                "size":{
                  "width":125,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfdc22e1753a42488d3ce61f4e1ca74b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":536,
              "y":1262},
            "size":{
              "width":139,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f2280f85d044cdd93a3fea022b84c30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":536,
                  "y":1262},
                "size":{
                  "width":139,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d427d5b97ce4ff1959ed8dcc398f087",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":536,
              "y":1288},
            "size":{
              "width":211,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21b6aa86985435e833a189fcc07ff45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":536,
                  "y":1288},
                "size":{
                  "width":211,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7da4ee4951a14daaa43da028bce4416b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":802,
              "y":1156},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd42d3657aea49c187079a072ebcc9ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":802,
                  "y":1156},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2248c86c1c0d479a9e70af837dfb4797",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":962,
              "y":1156},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4833c083d6374ab4b685fabe4c5594e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":962,
                  "y":1156},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05f2d7cc67324732854e95e86b073201",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":1104,
              "y":1154},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed7fb29beb5b4176bc2975e3da049bae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":1104,
                  "y":1154},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"202c8d11808141ec84a019a7244622bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":1362,
              "y":1156},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"919d41e035ad46eb81ad37eadc0609f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":1362,
                  "y":1156},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"833349b5c24a45ee93bc9a044d08aa05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":1222,
              "y":1153},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b8fa98a6ae04b2583f6f58a843749fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":1222,
                  "y":1153},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdf57b60cae744b4814d158441d424bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1368,
              "y":1186},
            "size":{
              "width":112,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5e12273604b43dcaec688b566cd99b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1368,
                  "y":1186},
                "size":{
                  "width":112,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u275.png"}},
{
          "id":"308277aaef154fe888451cc49394c71e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1372,
              "y":1296},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbd051eb9cd84ed5bb691d23c12dd0d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":1372,
                  "y":1296},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa60188def5741a5877b920cc1f85fdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":521,
              "y":1050},
            "size":{
              "width":1040,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa035665ed364832a4b41ab36b8f365a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":521,
                  "y":1050},
                "size":{
                  "width":1040,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cf8ac542be349aebb31405c69b78687",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"28px",
            "location":{
              "x":700,
              "y":1088},
            "size":{
              "width":817,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5fe772b84a642a5b5d3bcd653b30ab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"28px",
                "location":{
                  "x":700,
                  "y":1088},
                "size":{
                  "width":817,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d297af6c0a6c4d9fbf490c301dd0fb8c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":1020},
            "size":{
              "width":1190,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创客资讯/u84_line.png"}},
{
          "id":"71ed3acc9d4a42e3aff83bd57eea3478",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":967,
              "y":91},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e7cf7a7b2764e09a001ab9211089b1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":967,
                  "y":91},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"182932c2c8b54e6f82ee87941e8fd649",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEF4349,
              "opacity":1},
            "location":{
              "x":1424,
              "y":90},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c45b67ab864a428daf69f6645840de23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEF4349,
                  "opacity":1},
                "location":{
                  "x":1424,
                  "y":90},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 创客资讯",
                      "target":{
                        "targetType":"page",
                        "url":"创客资讯.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d99e1ae31c234001bc2153624632fd5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1068,
              "y":91},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed5fccba44734d22bce81fe7eb81d472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1068,
                  "y":91},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 梦想基金",
                      "target":{
                        "targetType":"page",
                        "url":"梦想基金.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f922b29a2d8f4569af7d3c5857a8c078",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1185,
              "y":91},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d29d915c7d04c6b8edc9ba8f1f237a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1185,
                  "y":91},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 工厂联盟",
                      "target":{
                        "targetType":"page",
                        "url":"工厂联盟.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de0fc6f0dac24d07a3fda05178af8c54",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1306,
              "y":91},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfdbed556d9f4ce29d337625bb704e30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1306,
                  "y":91},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 项目展示",
                      "target":{
                        "targetType":"page",
                        "url":"项目展示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a1766c34ddd14a41baf0ef6765fa5622":{
      "scriptId":"u0"},
    "9fb1a62a708d43a4aadf75fad6a8d6b5":{
      "scriptId":"u1"},
    "03e4c7b7ccbc4ef2908dcc6801452085":{
      "scriptId":"u2"},
    "c2472aea50ef44c9bd7c77158f7ee610":{
      "scriptId":"u3"},
    "27ec87a4cce440c68d858e83e9384627":{
      "scriptId":"u4"},
    "76b25837022642eca88434d4f39b4f6d":{
      "scriptId":"u5"},
    "a9eb91e1e86e48f3a0c2c3c905f5ba58":{
      "scriptId":"u6"},
    "7bf71b06c3b748499a63f982cac1df7d":{
      "scriptId":"u7"},
    "ad4a3fec3df54b0381f66d7d9f723148":{
      "scriptId":"u8"},
    "53fa5db354724584801e755e3a0ce58a":{
      "scriptId":"u9"},
    "9b5719051460410c93dd68eedc5585cf":{
      "scriptId":"u10"},
    "8e980ba8d3174364a11da33d42d1b6fe":{
      "scriptId":"u11"},
    "da55e65a56654a3c9b4fc81538545ee0":{
      "scriptId":"u12"},
    "89edbb79e26243bc91a5a20ad13dd253":{
      "scriptId":"u13"},
    "82ca7c2763494d37b714a697427be3ab":{
      "scriptId":"u14"},
    "875cef2a1139495398bab91d8b0429d2":{
      "scriptId":"u15"},
    "e75ecdfebba44fbba22b377bb12e95a7":{
      "scriptId":"u16"},
    "015585c7de3b48679743ffb75068ba29":{
      "scriptId":"u17"},
    "e7a1143e86d14cdd833609ce251f1c23":{
      "scriptId":"u18"},
    "aa79bfd34c554168bd4ba72e791fb612":{
      "scriptId":"u19"},
    "0c54518016bc456e8fa6bf252d1ce22e":{
      "scriptId":"u20"},
    "2deb4a144b5f46a0b49a273c10f4737f":{
      "scriptId":"u21"},
    "3a730ed4d6634010bdf62d9959250d90":{
      "scriptId":"u22"},
    "8c9eee0ca9dc4529918893becfcab736":{
      "scriptId":"u23"},
    "759f27a799944c028bb2fecc8c65e142":{
      "scriptId":"u24"},
    "f6a0827bb0984b20ae97c0bf82761987":{
      "scriptId":"u25"},
    "75cb586b51a64e5bb3a37b758fba9df8":{
      "scriptId":"u26"},
    "ec11ae283f16483e94f4827c005d2385":{
      "scriptId":"u27"},
    "f86444b59f334ede879ab1b18c07c635":{
      "scriptId":"u28"},
    "8d31e2582aee43c2a612eb3f5d52afc9":{
      "scriptId":"u29"},
    "3d2db47448634abcace4d74763f6e95e":{
      "scriptId":"u30"},
    "2bcb1368d5ec473e82746055d9f6a10e":{
      "scriptId":"u31"},
    "95c5dd84ed99419c8aee7b7d6e3ef987":{
      "scriptId":"u32"},
    "6aed5fcc2f6f479a8f7f5f06dfb30872":{
      "scriptId":"u33"},
    "04f4e0bf69c14831868546d9fbd8b235":{
      "scriptId":"u34"},
    "29c7e349ee4d4d1da6b9641a0fe39ef6":{
      "scriptId":"u35"},
    "6c66194352bb4f02904fa399364df7c9":{
      "scriptId":"u36"},
    "9b9d6050b9f54125878e239cee6d6f72":{
      "scriptId":"u37"},
    "79c8ed3fe8ad40f68664e5acf43cbb75":{
      "scriptId":"u38"},
    "35ad751eb7ef4290a1f1af18cc8acb0e":{
      "scriptId":"u39"},
    "2ece9f3bae814e5580f0056d37be6ad7":{
      "scriptId":"u40"},
    "d6e4fcc745134254a0308a7bf4534250":{
      "scriptId":"u41"},
    "42fc5572f9fd452d9b9fbec42b14c7fe":{
      "scriptId":"u42"},
    "4d3a63ddd60b451b8182af3ac7df46ac":{
      "scriptId":"u43"},
    "0d70af83852f48b5b25bc66b39172431":{
      "scriptId":"u44"},
    "f64d4543e2454f5faf435ea371fe4f31":{
      "scriptId":"u45"},
    "555a7191c6bd468689e2968e8cbd54d9":{
      "scriptId":"u46"},
    "f19296e01d8640fe891a6ebf1e65f540":{
      "scriptId":"u47"},
    "25fffc371ac14d7f8594dcb790100cbb":{
      "scriptId":"u48"},
    "24ecf040457745baad6e20a6055190b6":{
      "scriptId":"u49"},
    "3604dca8abea42d086bd896a9e165110":{
      "scriptId":"u50"},
    "087d468e406444d5b3d79d84ffa74cd3":{
      "scriptId":"u51"},
    "6ad9b4a042464fb5a0965333198fccff":{
      "scriptId":"u52"},
    "2af1af98e85f460599d3db1ecc5c9749":{
      "scriptId":"u53"},
    "ef96d140699e4e12af6d1f043478a1da":{
      "scriptId":"u54"},
    "30e2336a700a4cfdb34eb4d2ca8c3b71":{
      "scriptId":"u55"},
    "3b67b98bb699460c9b1e055e5d05b74f":{
      "scriptId":"u56"},
    "0d4fe5f943ab4478bec6cd3aab90501c":{
      "scriptId":"u57"},
    "1418e8565ded4cd7b36f8ea562429505":{
      "scriptId":"u58"},
    "4e744b65828845eeabb7bfb1978baf78":{
      "scriptId":"u59"},
    "da1bc00ebe364f62958dc359aa12c626":{
      "scriptId":"u60"},
    "e9ed3fd522e448339ac18f585869f468":{
      "scriptId":"u61"},
    "dfdc22e1753a42488d3ce61f4e1ca74b":{
      "scriptId":"u62"},
    "4f2280f85d044cdd93a3fea022b84c30":{
      "scriptId":"u63"},
    "6d427d5b97ce4ff1959ed8dcc398f087":{
      "scriptId":"u64"},
    "d21b6aa86985435e833a189fcc07ff45":{
      "scriptId":"u65"},
    "7da4ee4951a14daaa43da028bce4416b":{
      "scriptId":"u66"},
    "cd42d3657aea49c187079a072ebcc9ec":{
      "scriptId":"u67"},
    "2248c86c1c0d479a9e70af837dfb4797":{
      "scriptId":"u68"},
    "4833c083d6374ab4b685fabe4c5594e9":{
      "scriptId":"u69"},
    "05f2d7cc67324732854e95e86b073201":{
      "scriptId":"u70"},
    "ed7fb29beb5b4176bc2975e3da049bae":{
      "scriptId":"u71"},
    "202c8d11808141ec84a019a7244622bc":{
      "scriptId":"u72"},
    "919d41e035ad46eb81ad37eadc0609f1":{
      "scriptId":"u73"},
    "833349b5c24a45ee93bc9a044d08aa05":{
      "scriptId":"u74"},
    "5b8fa98a6ae04b2583f6f58a843749fa":{
      "scriptId":"u75"},
    "cdf57b60cae744b4814d158441d424bc":{
      "scriptId":"u76"},
    "e5e12273604b43dcaec688b566cd99b0":{
      "scriptId":"u77"},
    "308277aaef154fe888451cc49394c71e":{
      "scriptId":"u78"},
    "cbd051eb9cd84ed5bb691d23c12dd0d3":{
      "scriptId":"u79"},
    "aa60188def5741a5877b920cc1f85fdc":{
      "scriptId":"u80"},
    "aa035665ed364832a4b41ab36b8f365a":{
      "scriptId":"u81"},
    "7cf8ac542be349aebb31405c69b78687":{
      "scriptId":"u82"},
    "b5fe772b84a642a5b5d3bcd653b30ab6":{
      "scriptId":"u83"},
    "d297af6c0a6c4d9fbf490c301dd0fb8c":{
      "scriptId":"u84"},
    "71ed3acc9d4a42e3aff83bd57eea3478":{
      "scriptId":"u85"},
    "6e7cf7a7b2764e09a001ab9211089b1d":{
      "scriptId":"u86"},
    "182932c2c8b54e6f82ee87941e8fd649":{
      "scriptId":"u87"},
    "c45b67ab864a428daf69f6645840de23":{
      "scriptId":"u88"},
    "d99e1ae31c234001bc2153624632fd5d":{
      "scriptId":"u89"},
    "ed5fccba44734d22bce81fe7eb81d472":{
      "scriptId":"u90"},
    "f922b29a2d8f4569af7d3c5857a8c078":{
      "scriptId":"u91"},
    "9d29d915c7d04c6b8edc9ba8f1f237a5":{
      "scriptId":"u92"},
    "de0fc6f0dac24d07a3fda05178af8c54":{
      "scriptId":"u93"},
    "cfdbed556d9f4ce29d337625bb704e30":{
      "scriptId":"u94"}}});