$axure.loadCurrentPage({
  "url":"工厂联盟.html",
  "generationDate":new Date(1440388819676.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e8609dd639da4555837417fc426331b9",
    "type":"Axure:Page",
    "name":"工厂联盟",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"25310ba85575486d8d8a247c755636c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":152,
              "y":2},
            "size":{
              "width":1550,
              "height":33},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d66b709fea864cddad61581109b6282a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":152,
                  "y":2},
                "size":{
                  "width":1550,
                  "height":33},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u5.png"}},
{
          "id":"a32079a94aff4fd998c9b76f3bd7bab5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":450,
              "y":9},
            "size":{
              "width":183,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"325885473b40421cac08fc907e7bd6a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":450,
                  "y":9},
                "size":{
                  "width":183,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3889f2f0768f4b648681584573bab37e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1488,
              "y":9},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21d02f7c6c86489a9a000781b444b720",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1488,
                  "y":9},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf7aafdc1b3c4c819c4afa2f914b1e30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEF4349,
              "opacity":1},
            "location":{
              "x":1528,
              "y":9},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83e5a3ed97514f6fa098bc9fec7806d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEF4349,
                  "opacity":1},
                "location":{
                  "x":1528,
                  "y":9},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"447fead2299c4121b4339e6d94ae079a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1384,
              "y":9},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"742690c8e3e34a5c8292c320f5e36f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1384,
                  "y":9},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba5d0399c6ec42169cc71ff3af7143b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":56},
            "size":{
              "width":80,
              "height":70},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b78d018728742d786ef312d0af0fb77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":422,
                  "y":56},
                "size":{
                  "width":80,
                  "height":70},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u15.png"}},
{
          "id":"58fa6794df50445bbefaac405b40b915",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD0B068,
              "opacity":1},
            "location":{
              "x":521,
              "y":67},
            "size":{
              "width":41,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb6500d862404cc88edfa7e2a91e58a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD0B068,
                  "opacity":1},
                "location":{
                  "x":521,
                  "y":67},
                "size":{
                  "width":41,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34857011ed1646b5ba58e1af6fe6d1af",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":582,
              "y":83},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00ccc51a431b402a9c524eb40e4e282b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":582,
                  "y":83},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6264e0cdc1554029bef89f126c3a474e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":430,
              "y":99},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b0c254c55944168966e5e0483fe6c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":430,
                  "y":99},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29511a0b77f946349637ceb40a420917",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":5},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f873d53f762c4910b542a56b7419eb82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":412,
                  "y":5},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u149.png"}},
{
          "id":"8994184c2be9467d8217cd94b2596d28",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1517,
              "y":14},
            "size":{
              "width":10,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u151_line.png"}},
{
          "id":"87d2adf996ac43c0aaf627abbfaee290",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":957,
              "y":81},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d344aac843ca4c6896a03a3010379cbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":957,
                  "y":81},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81da4bab7fa645dc83491688198c2a01",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1414,
              "y":80},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a23eac1c7a546679975e7d8c66572be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1414,
                  "y":80},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 创客资讯",
                      "target":{
                        "targetType":"page",
                        "url":"创客资讯.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"256dd88a1db1421384a7cea20e384084",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1058,
              "y":81},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"648e789b93674474acbb4a764326aabe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1058,
                  "y":81},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 梦想基金",
                      "target":{
                        "targetType":"page",
                        "url":"梦想基金.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b5a09549e7847cf96af9f84bc91d0a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEF4349,
              "opacity":1},
            "location":{
              "x":1175,
              "y":81},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89b21360ef414e408640a19a72176ffc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEF4349,
                  "opacity":1},
                "location":{
                  "x":1175,
                  "y":81},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 工厂联盟",
                      "target":{
                        "targetType":"page",
                        "url":"工厂联盟.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f2847879d484262a480c90c55710623",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1296,
              "y":81},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc7e41bdb4fd48d8b98d36defa60ab81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1296,
                  "y":81},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 项目展示",
                      "target":{
                        "targetType":"page",
                        "url":"项目展示.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fb1bbd5f56f45d58acef53df3e63862",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF484B54},
            "location":{
              "x":130,
              "y":788},
            "size":{
              "width":1550,
              "height":223}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7982e4a40a2447b7845cc1d962d7f56e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF484B54},
                "location":{
                  "x":130,
                  "y":788},
                "size":{
                  "width":1550,
                  "height":223}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u253.png"}},
{
          "id":"e81dbe21c0ad4d3f878902630bb25c09",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD0B068,
              "opacity":1},
            "location":{
              "x":364,
              "y":830},
            "size":{
              "width":90,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9ad05ba1ffe4f14b9bf0af2e24b742e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD0B068,
                  "opacity":1},
                "location":{
                  "x":364,
                  "y":830},
                "size":{
                  "width":90,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e2663d2801149d7828468e4da592d99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":364,
              "y":864},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbcdcdaea01844e3ae4aa399ede6e67b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":364,
                  "y":864},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a022c0005ea948f4b8cb4885d890ad77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":364,
              "y":892},
            "size":{
              "width":125,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d73c3521a8704a84909e05398f78f4f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":364,
                  "y":892},
                "size":{
                  "width":125,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6ced38f2e66445c84763eb12488d68c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":364,
              "y":928},
            "size":{
              "width":139,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bb462fea2f94b40b6d97aea6264527c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":364,
                  "y":928},
                "size":{
                  "width":139,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a39e354b0ea14d349b3fdd0bcd569c68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":364,
              "y":954},
            "size":{
              "width":211,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"016f6e3d59ea4be5af02ded7c38a8e90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":364,
                  "y":954},
                "size":{
                  "width":211,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f807a373b4904dc68a519cbe361d9d48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":630,
              "y":822},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83303ec65de04a338c845871e38cef7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":630,
                  "y":822},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3496c32fc14b41aa9ffd3b520cdaa2a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":789,
              "y":822},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca96163b12724e31b253c7be8f8ad1bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":789,
                  "y":822},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd001f86f5844e66aa1c95bf23df0547",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":931,
              "y":820},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4931861717ab406d862a12b18aa34a1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":931,
                  "y":820},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fcf7eea0d354163bc177aac02c033d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":1190,
              "y":822},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98f5382a4dd941e497c3ed618fb988df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":1190,
                  "y":822},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87fa9ef381644dceaba1440a47663ad2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":1050,
              "y":818},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4921ae52e55404d9ff37263f51c7d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":1050,
                  "y":818},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbbcc547490e4d1b8ff8d9dd724088c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1196,
              "y":852},
            "size":{
              "width":112,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"496b2a461e9d40b3beda88d8e5ef71dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1196,
                  "y":852},
                "size":{
                  "width":112,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u275.png"}},
{
          "id":"706b05d2dfa74930aeb32d54ad95005b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1200,
              "y":962},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de44b4814a77406e972beb9864124a8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":1200,
                  "y":962},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a68ea78659ee415891c4bcaa8eaf290c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":530,
              "y":198},
            "size":{
              "width":170,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0783490304e9471dbe34a32f6716f023",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":530,
                  "y":198},
                "size":{
                  "width":170,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f7175dd9d884231aea87dc59d0f993f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":160},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f0fb970aa34c01bbd8f92dc68e94fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":160},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工厂联盟/u59.png"}},
{
          "id":"5a7b15e63f8b4a8d9bd71079e98afd4b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":136},
            "size":{
              "width":1550,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/项目展示/u153_line.png"}},
{
          "id":"4e0421d35da94275a61429c3d5b5c1a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEA8010},
            "location":{
              "x":1495,
              "y":198},
            "size":{
              "width":185,
              "height":52},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5914a29ccdf3468fa11014e3b12fb277",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEA8010},
                "location":{
                  "x":1495,
                  "y":198},
                "size":{
                  "width":185,
                  "height":52},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 个人中心",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/工厂联盟/u62.png"}},
{
          "id":"5cbfedf3c89142fa8fcc8688f6313af9",
          "label":"item2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"bold"}},
            "location":{
              "x":608,
              "y":270},
            "size":{
              "width":138,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03ff4d9dccb44ad9868b38492b1564ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"bold"}},
                "location":{
                  "x":608,
                  "y":270},
                "size":{
                  "width":138,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 当前部件 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setPanelOrder",
                      "description":"置 neirong 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["227203da489548999be6b012d6f2539e"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelOrder",
                      "description":"置 当前部件 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["5cbfedf3c89142fa8fcc8688f6313af9"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelState",
                      "description":"设置 neirong 到 [[this.name]]",
                      "panelsToStates":[{
                          "panelPath":["227203da489548999be6b012d6f2539e"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/工厂联盟/item2_u64.png",
            "selected~":"images/工厂联盟/item2_u64.png"}},
{
          "id":"c6cfee0755e84f0ba5f29a63aacafd16",
          "label":"item3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"bold"}},
            "location":{
              "x":746,
              "y":270},
            "size":{
              "width":138,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baa5c63b160e41b092742c38af07feb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"bold"}},
                "location":{
                  "x":746,
                  "y":270},
                "size":{
                  "width":138,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 当前部件 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setPanelOrder",
                      "description":"置 neirong 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["227203da489548999be6b012d6f2539e"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelOrder",
                      "description":"置 当前部件 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["c6cfee0755e84f0ba5f29a63aacafd16"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelState",
                      "description":"设置 neirong 到 [[this.name]]",
                      "panelsToStates":[{
                          "panelPath":["227203da489548999be6b012d6f2539e"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/工厂联盟/item2_u64.png",
            "selected~":"images/工厂联盟/item2_u64.png"}},
{
          "id":"a35e6b18df304b0188f96bd908abb1d5",
          "label":"item4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"bold"}},
            "location":{
              "x":884,
              "y":270},
            "size":{
              "width":138,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1818012adaf46dc956251aaf1088e5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"bold"}},
                "location":{
                  "x":884,
                  "y":270},
                "size":{
                  "width":138,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 当前部件 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setPanelOrder",
                      "description":"置 neirong 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["227203da489548999be6b012d6f2539e"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelOrder",
                      "description":"置 当前部件 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["a35e6b18df304b0188f96bd908abb1d5"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelState",
                      "description":"设置 neirong 到 [[this.name]]",
                      "panelsToStates":[{
                          "panelPath":["227203da489548999be6b012d6f2539e"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/工厂联盟/item2_u64.png",
            "selected~":"images/工厂联盟/item2_u64.png"}},
{
          "id":"227203da489548999be6b012d6f2539e",
          "label":"neirong",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":310},
            "size":{
              "width":1150,
              "height":460}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ca218d1e5aa44e64bb79b1dc934e293c",
              "label":"item1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"50ddbe1d82924728ac70cc8e1b6ebb72",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1149,
                      "height":459},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8783cb565b72491bba253706196994b7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1149,
                          "height":459},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/工厂联盟/u71.png"}},
{
                  "id":"83f09dc9a6fb4516ac20b0f6812c307d",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":40,
                      "y":40},
                    "size":{
                      "width":498,
                      "height":299}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b19b607314734669ae55f6291ac1823f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":40,
                          "y":40},
                        "size":{
                          "width":498,
                          "height":299}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/工厂联盟/u73.png"}},
{
                  "id":"d5eac5c7d32f4960bdcc0a6eafecfb6d",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "lineSpacing":"36px",
                    "location":{
                      "x":610,
                      "y":40},
                    "size":{
                      "width":200,
                      "height":330}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a3f2b3dc43ad4a3fb1ee0a4211041ea0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "lineSpacing":"36px",
                        "location":{
                          "x":610,
                          "y":40},
                        "size":{
                          "width":200,
                          "height":330}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"98a06d3789004d338b801823d7e1f376",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "lineSpacing":"36px",
                    "location":{
                      "x":850,
                      "y":40},
                    "size":{
                      "width":250,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4e5093e9fd648e682e27922a6f8a5cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "lineSpacing":"36px",
                        "location":{
                          "x":850,
                          "y":40},
                        "size":{
                          "width":250,
                          "height":180}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"8b4ea7cb028b4d18bb36e300a8f7d223",
              "label":"item2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"96145c9cdd324d82aee9b8b8c2ece73d",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1150,
                      "height":460},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b3dd7b8eab214f02acdc6e0cdaaffe00",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1150,
                          "height":460},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/工厂联盟/u79.png"}},
{
                  "id":"91c8d24f19df497b9a69fdee34796c9c",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "lineSpacing":"36px",
                    "location":{
                      "x":600,
                      "y":106},
                    "size":{
                      "width":240,
                      "height":322}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"014fe4ad61e64fa984d1d27ff6ddf70c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "lineSpacing":"36px",
                        "location":{
                          "x":600,
                          "y":106},
                        "size":{
                          "width":240,
                          "height":322}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6b90a3315c1e4af2983fe19a13474c4d",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "lineSpacing":"36px",
                    "location":{
                      "x":870,
                      "y":106},
                    "size":{
                      "width":230,
                      "height":324}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c1f1c13b3d24d09a13fb88d8ac03024",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "lineSpacing":"36px",
                        "location":{
                          "x":870,
                          "y":106},
                        "size":{
                          "width":230,
                          "height":324}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"74d2c548c5fc45d3b941d94a381f0f97",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":90},
                    "size":{
                      "width":470,
                      "height":330}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf91f00d00e84c2abf25ee0a5b71e882",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":90},
                        "size":{
                          "width":470,
                          "height":330}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/工厂联盟/u85.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0212d6e6d8af4524b221bae52ca686ad",
              "label":"item3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8e22aef15406419f9c907a8649a7d434",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1149,
                      "height":459},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0bb81027a06d49b9954ffb68ac6a5492",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1149,
                          "height":459},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/工厂联盟/u71.png"}},
{
                  "id":"0b7381bdfeac4cffbdf4601ede08e1bf",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "lineSpacing":"36px",
                    "location":{
                      "x":590,
                      "y":14},
                    "size":{
                      "width":200,
                      "height":432}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09fe9bd5d356415db6b897e694941470",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "lineSpacing":"36px",
                        "location":{
                          "x":590,
                          "y":14},
                        "size":{
                          "width":200,
                          "height":432}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"131556dbd7054415ae27d9887af4528a",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "lineSpacing":"36px",
                    "location":{
                      "x":880,
                      "y":10},
                    "size":{
                      "width":200,
                      "height":439}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e204feef78e4e078192dc85cd5dc496",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "lineSpacing":"36px",
                        "location":{
                          "x":880,
                          "y":10},
                        "size":{
                          "width":200,
                          "height":439}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ce3b969b4a2d474e89629b47c60a53cd",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":25},
                    "size":{
                      "width":520,
                      "height":375}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af0192ce5e2445e1bb4829fb59f4e444",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":25},
                        "size":{
                          "width":520,
                          "height":375}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/工厂联盟/u93.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"4e5f1147775840bfa8ed5d6b4a7d99a7",
              "label":"item4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2c6ab4450632406b9fa8b2c5ebc979f7",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1149,
                      "height":459},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41cad892a0b944e384b977b278582e99",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1149,
                          "height":459},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/工厂联盟/u71.png"}},
{
                  "id":"ac46dd7ec8044230a2ceeae9eeb2abd5",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":3,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":20},
                    "size":{
                      "width":492,
                      "height":390},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4afa3f3b84354ac2ba79ab6ef7207f33",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":20},
                        "size":{
                          "width":492,
                          "height":390},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/工厂联盟/u97.png"}},
{
                  "id":"5e2cf38fbe0442e9a9a8bba4597cd584",
                  "label":"",
                  "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "lineSpacing":"36px",
                    "location":{
                      "x":630,
                      "y":74},
                    "size":{
                      "width":330,
                      "height":216}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5df95863b9db42628638d97fcbc6960d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"227203da489548999be6b012d6f2539e",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "lineSpacing":"36px",
                        "location":{
                          "x":630,
                          "y":74},
                        "size":{
                          "width":330,
                          "height":216}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"5079642d012e4191858abe9cd50e97f3",
          "label":"item1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"bold"}},
            "location":{
              "x":470,
              "y":270},
            "size":{
              "width":138,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08a175010da14728916e8f05f897b503",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"bold"}},
                "location":{
                  "x":470,
                  "y":270},
                "size":{
                  "width":138,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 当前部件 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setPanelOrder",
                      "description":"置 neirong 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["227203da489548999be6b012d6f2539e"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelOrder",
                      "description":"置 当前部件 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["5079642d012e4191858abe9cd50e97f3"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelState",
                      "description":"设置 neirong 到 [[this.name]]",
                      "panelsToStates":[{
                          "panelPath":["227203da489548999be6b012d6f2539e"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/工厂联盟/item2_u64.png",
            "selected~":"images/工厂联盟/item2_u64.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "25310ba85575486d8d8a247c755636c6":{
      "scriptId":"u0"},
    "d66b709fea864cddad61581109b6282a":{
      "scriptId":"u1"},
    "a32079a94aff4fd998c9b76f3bd7bab5":{
      "scriptId":"u2"},
    "325885473b40421cac08fc907e7bd6a9":{
      "scriptId":"u3"},
    "3889f2f0768f4b648681584573bab37e":{
      "scriptId":"u4"},
    "21d02f7c6c86489a9a000781b444b720":{
      "scriptId":"u5"},
    "bf7aafdc1b3c4c819c4afa2f914b1e30":{
      "scriptId":"u6"},
    "83e5a3ed97514f6fa098bc9fec7806d9":{
      "scriptId":"u7"},
    "447fead2299c4121b4339e6d94ae079a":{
      "scriptId":"u8"},
    "742690c8e3e34a5c8292c320f5e36f00":{
      "scriptId":"u9"},
    "ba5d0399c6ec42169cc71ff3af7143b1":{
      "scriptId":"u10"},
    "0b78d018728742d786ef312d0af0fb77":{
      "scriptId":"u11"},
    "58fa6794df50445bbefaac405b40b915":{
      "scriptId":"u12"},
    "bb6500d862404cc88edfa7e2a91e58a3":{
      "scriptId":"u13"},
    "34857011ed1646b5ba58e1af6fe6d1af":{
      "scriptId":"u14"},
    "00ccc51a431b402a9c524eb40e4e282b":{
      "scriptId":"u15"},
    "6264e0cdc1554029bef89f126c3a474e":{
      "scriptId":"u16"},
    "b9b0c254c55944168966e5e0483fe6c0":{
      "scriptId":"u17"},
    "29511a0b77f946349637ceb40a420917":{
      "scriptId":"u18"},
    "f873d53f762c4910b542a56b7419eb82":{
      "scriptId":"u19"},
    "8994184c2be9467d8217cd94b2596d28":{
      "scriptId":"u20"},
    "87d2adf996ac43c0aaf627abbfaee290":{
      "scriptId":"u21"},
    "d344aac843ca4c6896a03a3010379cbb":{
      "scriptId":"u22"},
    "81da4bab7fa645dc83491688198c2a01":{
      "scriptId":"u23"},
    "0a23eac1c7a546679975e7d8c66572be":{
      "scriptId":"u24"},
    "256dd88a1db1421384a7cea20e384084":{
      "scriptId":"u25"},
    "648e789b93674474acbb4a764326aabe":{
      "scriptId":"u26"},
    "5b5a09549e7847cf96af9f84bc91d0a3":{
      "scriptId":"u27"},
    "89b21360ef414e408640a19a72176ffc":{
      "scriptId":"u28"},
    "9f2847879d484262a480c90c55710623":{
      "scriptId":"u29"},
    "bc7e41bdb4fd48d8b98d36defa60ab81":{
      "scriptId":"u30"},
    "2fb1bbd5f56f45d58acef53df3e63862":{
      "scriptId":"u31"},
    "7982e4a40a2447b7845cc1d962d7f56e":{
      "scriptId":"u32"},
    "e81dbe21c0ad4d3f878902630bb25c09":{
      "scriptId":"u33"},
    "f9ad05ba1ffe4f14b9bf0af2e24b742e":{
      "scriptId":"u34"},
    "2e2663d2801149d7828468e4da592d99":{
      "scriptId":"u35"},
    "fbcdcdaea01844e3ae4aa399ede6e67b":{
      "scriptId":"u36"},
    "a022c0005ea948f4b8cb4885d890ad77":{
      "scriptId":"u37"},
    "d73c3521a8704a84909e05398f78f4f9":{
      "scriptId":"u38"},
    "b6ced38f2e66445c84763eb12488d68c":{
      "scriptId":"u39"},
    "0bb462fea2f94b40b6d97aea6264527c":{
      "scriptId":"u40"},
    "a39e354b0ea14d349b3fdd0bcd569c68":{
      "scriptId":"u41"},
    "016f6e3d59ea4be5af02ded7c38a8e90":{
      "scriptId":"u42"},
    "f807a373b4904dc68a519cbe361d9d48":{
      "scriptId":"u43"},
    "83303ec65de04a338c845871e38cef7e":{
      "scriptId":"u44"},
    "3496c32fc14b41aa9ffd3b520cdaa2a7":{
      "scriptId":"u45"},
    "ca96163b12724e31b253c7be8f8ad1bb":{
      "scriptId":"u46"},
    "dd001f86f5844e66aa1c95bf23df0547":{
      "scriptId":"u47"},
    "4931861717ab406d862a12b18aa34a1c":{
      "scriptId":"u48"},
    "5fcf7eea0d354163bc177aac02c033d2":{
      "scriptId":"u49"},
    "98f5382a4dd941e497c3ed618fb988df":{
      "scriptId":"u50"},
    "87fa9ef381644dceaba1440a47663ad2":{
      "scriptId":"u51"},
    "e4921ae52e55404d9ff37263f51c7d3b":{
      "scriptId":"u52"},
    "bbbcc547490e4d1b8ff8d9dd724088c5":{
      "scriptId":"u53"},
    "496b2a461e9d40b3beda88d8e5ef71dd":{
      "scriptId":"u54"},
    "706b05d2dfa74930aeb32d54ad95005b":{
      "scriptId":"u55"},
    "de44b4814a77406e972beb9864124a8b":{
      "scriptId":"u56"},
    "a68ea78659ee415891c4bcaa8eaf290c":{
      "scriptId":"u57"},
    "0783490304e9471dbe34a32f6716f023":{
      "scriptId":"u58"},
    "7f7175dd9d884231aea87dc59d0f993f":{
      "scriptId":"u59"},
    "70f0fb970aa34c01bbd8f92dc68e94fa":{
      "scriptId":"u60"},
    "5a7b15e63f8b4a8d9bd71079e98afd4b":{
      "scriptId":"u61"},
    "4e0421d35da94275a61429c3d5b5c1a7":{
      "scriptId":"u62"},
    "5914a29ccdf3468fa11014e3b12fb277":{
      "scriptId":"u63"},
    "5cbfedf3c89142fa8fcc8688f6313af9":{
      "scriptId":"u64"},
    "03ff4d9dccb44ad9868b38492b1564ce":{
      "scriptId":"u65"},
    "c6cfee0755e84f0ba5f29a63aacafd16":{
      "scriptId":"u66"},
    "baa5c63b160e41b092742c38af07feb6":{
      "scriptId":"u67"},
    "a35e6b18df304b0188f96bd908abb1d5":{
      "scriptId":"u68"},
    "b1818012adaf46dc956251aaf1088e5c":{
      "scriptId":"u69"},
    "227203da489548999be6b012d6f2539e":{
      "scriptId":"u70"},
    "50ddbe1d82924728ac70cc8e1b6ebb72":{
      "scriptId":"u71"},
    "8783cb565b72491bba253706196994b7":{
      "scriptId":"u72"},
    "83f09dc9a6fb4516ac20b0f6812c307d":{
      "scriptId":"u73"},
    "b19b607314734669ae55f6291ac1823f":{
      "scriptId":"u74"},
    "d5eac5c7d32f4960bdcc0a6eafecfb6d":{
      "scriptId":"u75"},
    "a3f2b3dc43ad4a3fb1ee0a4211041ea0":{
      "scriptId":"u76"},
    "98a06d3789004d338b801823d7e1f376":{
      "scriptId":"u77"},
    "e4e5093e9fd648e682e27922a6f8a5cd":{
      "scriptId":"u78"},
    "96145c9cdd324d82aee9b8b8c2ece73d":{
      "scriptId":"u79"},
    "b3dd7b8eab214f02acdc6e0cdaaffe00":{
      "scriptId":"u80"},
    "91c8d24f19df497b9a69fdee34796c9c":{
      "scriptId":"u81"},
    "014fe4ad61e64fa984d1d27ff6ddf70c":{
      "scriptId":"u82"},
    "6b90a3315c1e4af2983fe19a13474c4d":{
      "scriptId":"u83"},
    "5c1f1c13b3d24d09a13fb88d8ac03024":{
      "scriptId":"u84"},
    "74d2c548c5fc45d3b941d94a381f0f97":{
      "scriptId":"u85"},
    "cf91f00d00e84c2abf25ee0a5b71e882":{
      "scriptId":"u86"},
    "8e22aef15406419f9c907a8649a7d434":{
      "scriptId":"u87"},
    "0bb81027a06d49b9954ffb68ac6a5492":{
      "scriptId":"u88"},
    "0b7381bdfeac4cffbdf4601ede08e1bf":{
      "scriptId":"u89"},
    "09fe9bd5d356415db6b897e694941470":{
      "scriptId":"u90"},
    "131556dbd7054415ae27d9887af4528a":{
      "scriptId":"u91"},
    "9e204feef78e4e078192dc85cd5dc496":{
      "scriptId":"u92"},
    "ce3b969b4a2d474e89629b47c60a53cd":{
      "scriptId":"u93"},
    "af0192ce5e2445e1bb4829fb59f4e444":{
      "scriptId":"u94"},
    "2c6ab4450632406b9fa8b2c5ebc979f7":{
      "scriptId":"u95"},
    "41cad892a0b944e384b977b278582e99":{
      "scriptId":"u96"},
    "ac46dd7ec8044230a2ceeae9eeb2abd5":{
      "scriptId":"u97"},
    "4afa3f3b84354ac2ba79ab6ef7207f33":{
      "scriptId":"u98"},
    "5e2cf38fbe0442e9a9a8bba4597cd584":{
      "scriptId":"u99"},
    "5df95863b9db42628638d97fcbc6960d":{
      "scriptId":"u100"},
    "5079642d012e4191858abe9cd50e97f3":{
      "scriptId":"u101"},
    "08a175010da14728916e8f05f897b503":{
      "scriptId":"u102"}}});