$axure.loadCurrentPage({
  "url":"梦想基金.html",
  "generationDate":new Date(1441187832288.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"68bf5263a8404e0f9627e22cdad1be84",
    "type":"Axure:Page",
    "name":"梦想基金",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d0bee58f372b435f8de98cf95f691229",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":20,
              "y":124},
            "size":{
              "width":1330,
              "height":1786},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"862eac6d1e854fa88f8ebb6067773ffe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":20,
                  "y":124},
                "size":{
                  "width":1330,
                  "height":1786},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/梦想基金/u0.png"}},
{
          "id":"abf40dc14b5d49f7b6c2c5e1709e678a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":2126},
            "size":{
              "width":1330,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c77821a51c344d4a8fe1440f5db12924",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":2126},
                "size":{
                  "width":1330,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"968a5eb5e8f840b9a39ae22277166d38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":1960},
            "size":{
              "width":1330,
              "height":166},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d140ac27656e44608fa138cf0e88be7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":1960},
                "size":{
                  "width":1330,
                  "height":166},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"2f47b949666b4696a79be4d2db0b7644",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":800,
              "y":2000},
            "size":{
              "width":349,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae08b4a55f3b4c8f82665b13f60b5800",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":800,
                  "y":2000},
                "size":{
                  "width":349,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf5410322c8b4470953e4040fc2c4b67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":622,
              "y":1994},
            "size":{
              "width":87,
              "height":82},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90ee168c000741f496a0455f446f9a98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":622,
                  "y":1994},
                "size":{
                  "width":87,
                  "height":82},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"bf6aea84d5c848288c109d870f9a42af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1360,
              "y":18},
            "size":{
              "width":86,
              "height":156},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd5f18dbf2c34983bc836cd0dc9cb79e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1360,
                  "y":18},
                "size":{
                  "width":86,
                  "height":156},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u18.png"}},
{
          "id":"926e4b622037465b87a94e5edcb5f16c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":622,
              "y":2082},
            "size":{
              "width":98,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70c114e915864b15a75f27f48c3371bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":622,
                  "y":2082},
                "size":{
                  "width":98,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"431d83bccba7441faded0b99fba35f4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":265,
              "y":1985},
            "size":{
              "width":200,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0696d96176394a97b6249ba1541976fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":265,
                  "y":1985},
                "size":{
                  "width":200,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06813c8b1b394c9eab29ba2d5aac9ebf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":124},
            "size":{
              "width":1330,
              "height":282},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c514d632f2d64a98932a256a4e72fc0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":124},
                "size":{
                  "width":1330,
                  "height":282},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/梦想基金/u16.png"}},
{
          "id":"11b4e9c1f3144bc797d85c27dbd7abd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":104,
              "y":164},
            "size":{
              "width":636,
              "height":203},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36eb4b4da58b4a489de6a17779dd7f4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":104,
                  "y":164},
                "size":{
                  "width":636,
                  "height":203},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/梦想基金/u18.png"}},
{
          "id":"2c0502334c3349589f0d8e9c4ee3c736",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":104,
              "y":441},
            "size":{
              "width":740,
              "height":440},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8da15a2542d94f1e8da5764d0d61b900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":104,
                  "y":441},
                "size":{
                  "width":740,
                  "height":440},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/梦想基金/u20.png"}},
{
          "id":"405667efe787433f81df70d3c8546e2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "location":{
              "x":880,
              "y":470},
            "size":{
              "width":400,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c714bf2edd6b4077a307668df65193af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "location":{
                  "x":880,
                  "y":470},
                "size":{
                  "width":400,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8746c7172ac4dc18cab9c477347fa2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":920,
              "y":548},
            "size":{
              "width":360,
              "height":304}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8762b0b922be4d11bb8b2a1c66b4c768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":920,
                  "y":548},
                "size":{
                  "width":360,
                  "height":304}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19702e06e5474cc6ae338e677292ef69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":915},
            "size":{
              "width":1330,
              "height":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caba0aced7294a1f985c24913e846c02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":915},
                "size":{
                  "width":1330,
                  "height":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/梦想基金/u26.png"}},
{
          "id":"8a93a1d65ea44b68af75abf461483d0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":950},
            "size":{
              "width":740,
              "height":440},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baad1899d22549608eba9d40191c5e2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":950},
                "size":{
                  "width":740,
                  "height":440},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/梦想基金/u28.png"}},
{
          "id":"ebda1b1b76fb47a1b66e9562a9d206e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":104,
              "y":979},
            "size":{
              "width":400,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fd6cb38e3eb4bc4a1bad55241d66a04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":104,
                  "y":979},
                "size":{
                  "width":400,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b0ef3a6de034c72abd9a0cf10412b78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":1057},
            "size":{
              "width":360,
              "height":304}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5721dab0fac44d43864ff7bdbebdfcf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":1057},
                "size":{
                  "width":360,
                  "height":304}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1beec5a79ce24458985a4ef0a739d314",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":20,
              "y":1424},
            "size":{
              "width":1330,
              "height":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05c30f5b408241e0b9d9e9d9d59b5686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":1424},
                "size":{
                  "width":1330,
                  "height":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/梦想基金/u34.png"}},
{
          "id":"edfdfccce15944df8972d141b93c770a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":104,
              "y":1459},
            "size":{
              "width":740,
              "height":440},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c844b36f91742b28b17f2620f517086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":104,
                  "y":1459},
                "size":{
                  "width":740,
                  "height":440},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/梦想基金/u20.png"}},
{
          "id":"ba2296af538f404a978510ad186e1468",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"right",
            "location":{
              "x":880,
              "y":1488},
            "size":{
              "width":400,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38d9a13b6ad9481e81585c134a362bb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"right",
                "location":{
                  "x":880,
                  "y":1488},
                "size":{
                  "width":400,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8519dc8c59fb47af9d71a18ee6a13449",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":920,
              "y":1566},
            "size":{
              "width":360,
              "height":304}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16be15891ffc4a60867e40fef60fcdf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":920,
                  "y":1566},
                "size":{
                  "width":360,
                  "height":304}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08888b40246e4541853b128dc01dac0d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":18}},
          "adaptiveStyles":{
},
          "masterId":"6fe4af5c80ef4df0bff6cc8d9e4ba33a"}]}},
  "masters":{
    "6fe4af5c80ef4df0bff6cc8d9e4ba33a":{
      "packageId":"6fe4af5c80ef4df0bff6cc8d9e4ba33a",
      "type":"Axure:Master",
      "name":"顶部",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3749e4072ec14133adc397b3df858f62",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1330,
                "height":107},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8b30f18dd8d14d338b226883dbc9bdc5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1330,
                    "height":107},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u182.png"}},
{
            "id":"112de89ef0f64661962943331402d51b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF1E1E1E,
                "opacity":1},
              "location":{
                "x":179,
                "y":30},
              "size":{
                "width":41,
                "height":48}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"62133f8da24143bea2b1396c400451bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF1E1E1E,
                    "opacity":1},
                  "location":{
                    "x":179,
                    "y":30},
                  "size":{
                    "width":41,
                    "height":48}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dd62f6cec3d74e9e88997d757cca754b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"14px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF1E1E1E,
                "opacity":1},
              "location":{
                "x":231,
                "y":46},
              "size":{
                "width":127,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1cae6ba755fb4ecf9bce7431c9dc81f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF1E1E1E,
                    "opacity":1},
                  "location":{
                    "x":231,
                    "y":46},
                  "size":{
                    "width":127,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"86f53a193d784761a954ab959b6b843a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033FF,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}},
                "mouseDown":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}},
                "selected":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}}},
              "location":{
                "x":572,
                "y":44},
              "size":{
                "width":33,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"795933f306504bd898f81d520d17bbe8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033FF,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}},
                    "mouseDown":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}},
                    "selected":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}}},
                  "location":{
                    "x":572,
                    "y":44},
                  "size":{
                    "width":33,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"57fb7aba565648b1b3bcc4f1a881419c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033FF,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}},
                "mouseDown":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}},
                "selected":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}}},
              "location":{
                "x":1030,
                "y":44},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce219bffafe9414b88afc2884c053ed2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033FF,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}},
                    "mouseDown":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}},
                    "selected":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}}},
                  "location":{
                    "x":1030,
                    "y":44},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 创客资讯",
                        "target":{
                          "targetType":"page",
                          "url":"创客资讯.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"8c810358863944f0a89e141c6155731b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033FF,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}},
                "mouseDown":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}},
                "selected":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}}},
              "location":{
                "x":674,
                "y":44},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6c06bb86544848e594bd38e80fae2ee1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033FF,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}},
                    "mouseDown":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}},
                    "selected":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}}},
                  "location":{
                    "x":674,
                    "y":44},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 梦想基金",
                        "target":{
                          "targetType":"page",
                          "url":"梦想基金.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"0283fefff85149499e16dc47f37a7cf3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033FF,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}},
                "mouseDown":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}},
                "selected":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}}},
              "location":{
                "x":790,
                "y":44},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23444e81c2ce4e4a8ce220ce6b0bf6d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033FF,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}},
                    "mouseDown":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}},
                    "selected":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}}},
                  "location":{
                    "x":790,
                    "y":44},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 科技孵化",
                        "target":{
                          "targetType":"page",
                          "url":"科技孵化.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"150a14daf28343f897c0dc51fa9de761",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033FF,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}},
                "mouseDown":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}},
                "selected":{
                  "fontWeight":"bold",
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":153,
                      "g":153,
                      "b":153,
                      "a":0.647058823529412}}}},
              "location":{
                "x":912,
                "y":44},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"391068c11d5f49babaf7a790b8deb8c3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033FF,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}},
                    "mouseDown":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}},
                    "selected":{
                      "fontWeight":"bold",
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":153,
                          "g":153,
                          "b":153,
                          "a":0.647058823529412}}}},
                  "location":{
                    "x":912,
                    "y":44},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 项目中心",
                        "target":{
                          "targetType":"page",
                          "url":"项目中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"149b4921857d43a4af370631b4ff3117",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF1E1E1E,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":63,
                "y":18},
              "size":{
                "width":107,
                "height":70},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b45cd1ed965e431c8ad311a5ebaff730",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF1E1E1E,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":63,
                    "y":18},
                  "size":{
                    "width":107,
                    "height":70},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u198.png"}},
{
            "id":"b7afe7fc3d2d4b759dd7d00eb88132c1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033FF,
                "opacity":1},
              "location":{
                "x":1170,
                "y":45},
              "size":{
                "width":29,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9e775bb7b5074d76a0ab2731dfe61732",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033FF,
                    "opacity":1},
                  "location":{
                    "x":1170,
                    "y":45},
                  "size":{
                    "width":29,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce657869ca1941bf9b0c38296089473a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF1E1E1E,
                "opacity":1},
              "location":{
                "x":1251,
                "y":45},
              "size":{
                "width":29,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ea6c7b05ee243cc9124a9cedf57f103",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF1E1E1E,
                    "opacity":1},
                  "location":{
                    "x":1251,
                    "y":45},
                  "size":{
                    "width":29,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"009f8c77f728499c86b05157534191c7",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1236,
                "y":48},
              "size":{
                "width":10,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/梦想基金/u65_line.png"}},
{
            "id":"e07a2a1f0baa4520a8437c8f6f2b4e9b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1209,
                "y":45},
              "size":{
                "width":21,
                "height":21},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"063c0a60809c4a5ba96b98b1354b44ff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1209,
                    "y":45},
                  "size":{
                    "width":21,
                    "height":21},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/梦想基金/u66.png"}}]}}},
  "objectPaths":{
    "d0bee58f372b435f8de98cf95f691229":{
      "scriptId":"u0"},
    "862eac6d1e854fa88f8ebb6067773ffe":{
      "scriptId":"u1"},
    "abf40dc14b5d49f7b6c2c5e1709e678a":{
      "scriptId":"u2"},
    "c77821a51c344d4a8fe1440f5db12924":{
      "scriptId":"u3"},
    "968a5eb5e8f840b9a39ae22277166d38":{
      "scriptId":"u4"},
    "d140ac27656e44608fa138cf0e88be7e":{
      "scriptId":"u5"},
    "2f47b949666b4696a79be4d2db0b7644":{
      "scriptId":"u6"},
    "ae08b4a55f3b4c8f82665b13f60b5800":{
      "scriptId":"u7"},
    "bf5410322c8b4470953e4040fc2c4b67":{
      "scriptId":"u8"},
    "90ee168c000741f496a0455f446f9a98":{
      "scriptId":"u9"},
    "bf6aea84d5c848288c109d870f9a42af":{
      "scriptId":"u10"},
    "cd5f18dbf2c34983bc836cd0dc9cb79e":{
      "scriptId":"u11"},
    "926e4b622037465b87a94e5edcb5f16c":{
      "scriptId":"u12"},
    "70c114e915864b15a75f27f48c3371bc":{
      "scriptId":"u13"},
    "431d83bccba7441faded0b99fba35f4e":{
      "scriptId":"u14"},
    "0696d96176394a97b6249ba1541976fa":{
      "scriptId":"u15"},
    "06813c8b1b394c9eab29ba2d5aac9ebf":{
      "scriptId":"u16"},
    "c514d632f2d64a98932a256a4e72fc0f":{
      "scriptId":"u17"},
    "11b4e9c1f3144bc797d85c27dbd7abd4":{
      "scriptId":"u18"},
    "36eb4b4da58b4a489de6a17779dd7f4d":{
      "scriptId":"u19"},
    "2c0502334c3349589f0d8e9c4ee3c736":{
      "scriptId":"u20"},
    "8da15a2542d94f1e8da5764d0d61b900":{
      "scriptId":"u21"},
    "405667efe787433f81df70d3c8546e2e":{
      "scriptId":"u22"},
    "c714bf2edd6b4077a307668df65193af":{
      "scriptId":"u23"},
    "a8746c7172ac4dc18cab9c477347fa2a":{
      "scriptId":"u24"},
    "8762b0b922be4d11bb8b2a1c66b4c768":{
      "scriptId":"u25"},
    "19702e06e5474cc6ae338e677292ef69":{
      "scriptId":"u26"},
    "caba0aced7294a1f985c24913e846c02":{
      "scriptId":"u27"},
    "8a93a1d65ea44b68af75abf461483d0e":{
      "scriptId":"u28"},
    "baad1899d22549608eba9d40191c5e2c":{
      "scriptId":"u29"},
    "ebda1b1b76fb47a1b66e9562a9d206e5":{
      "scriptId":"u30"},
    "4fd6cb38e3eb4bc4a1bad55241d66a04":{
      "scriptId":"u31"},
    "6b0ef3a6de034c72abd9a0cf10412b78":{
      "scriptId":"u32"},
    "5721dab0fac44d43864ff7bdbebdfcf6":{
      "scriptId":"u33"},
    "1beec5a79ce24458985a4ef0a739d314":{
      "scriptId":"u34"},
    "05c30f5b408241e0b9d9e9d9d59b5686":{
      "scriptId":"u35"},
    "edfdfccce15944df8972d141b93c770a":{
      "scriptId":"u36"},
    "7c844b36f91742b28b17f2620f517086":{
      "scriptId":"u37"},
    "ba2296af538f404a978510ad186e1468":{
      "scriptId":"u38"},
    "38d9a13b6ad9481e81585c134a362bb4":{
      "scriptId":"u39"},
    "8519dc8c59fb47af9d71a18ee6a13449":{
      "scriptId":"u40"},
    "16be15891ffc4a60867e40fef60fcdf9":{
      "scriptId":"u41"},
    "08888b40246e4541853b128dc01dac0d":{
      "scriptId":"u42",
      "3749e4072ec14133adc397b3df858f62":{
        "scriptId":"u43"},
      "8b30f18dd8d14d338b226883dbc9bdc5":{
        "scriptId":"u44"},
      "112de89ef0f64661962943331402d51b":{
        "scriptId":"u45"},
      "62133f8da24143bea2b1396c400451bc":{
        "scriptId":"u46"},
      "dd62f6cec3d74e9e88997d757cca754b":{
        "scriptId":"u47"},
      "1cae6ba755fb4ecf9bce7431c9dc81f3":{
        "scriptId":"u48"},
      "86f53a193d784761a954ab959b6b843a":{
        "scriptId":"u49"},
      "795933f306504bd898f81d520d17bbe8":{
        "scriptId":"u50"},
      "57fb7aba565648b1b3bcc4f1a881419c":{
        "scriptId":"u51"},
      "ce219bffafe9414b88afc2884c053ed2":{
        "scriptId":"u52"},
      "8c810358863944f0a89e141c6155731b":{
        "scriptId":"u53"},
      "6c06bb86544848e594bd38e80fae2ee1":{
        "scriptId":"u54"},
      "0283fefff85149499e16dc47f37a7cf3":{
        "scriptId":"u55"},
      "23444e81c2ce4e4a8ce220ce6b0bf6d4":{
        "scriptId":"u56"},
      "150a14daf28343f897c0dc51fa9de761":{
        "scriptId":"u57"},
      "391068c11d5f49babaf7a790b8deb8c3":{
        "scriptId":"u58"},
      "149b4921857d43a4af370631b4ff3117":{
        "scriptId":"u59"},
      "b45cd1ed965e431c8ad311a5ebaff730":{
        "scriptId":"u60"},
      "b7afe7fc3d2d4b759dd7d00eb88132c1":{
        "scriptId":"u61"},
      "9e775bb7b5074d76a0ab2731dfe61732":{
        "scriptId":"u62"},
      "ce657869ca1941bf9b0c38296089473a":{
        "scriptId":"u63"},
      "6ea6c7b05ee243cc9124a9cedf57f103":{
        "scriptId":"u64"},
      "009f8c77f728499c86b05157534191c7":{
        "scriptId":"u65"},
      "e07a2a1f0baa4520a8437c8f6f2b4e9b":{
        "scriptId":"u66"},
      "063c0a60809c4a5ba96b98b1354b44ff":{
        "scriptId":"u67"}}}});